import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import "./globals.css";
import AuthProvider from "./providers/AuthProvider";
import Header from "../../components/Header";
import Footer from "../../components/Footer";

export const metadata = {
  title: "Next Starter Kit",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider>
          <Header />
          <AuthProvider>{children}</AuthProvider>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
